#!/system/bin/sh
#-GGWP-Beta Edition >>Cleaner.. Pre Tested on CM 12.1 <<#
#This Script For Xiaomi Redmi 2 1gb and 2gb version version#
#Thanks to Slaid for Fly On#
#Follow My Project on Github joshuacontantine.k#
#Follow me in XDA joshuaconstantine@xda#
#This is Beta Project#
#This is open source#
Interval between cleaner runs,in seconds, 43200=12 hours
RUN_EVERY=43200


FLY=/data/Fly-On/08cleaner.log

busybox rm -f 

$FLY
busybox touch $FLY

echo "# Fly-On Mod™ LOGGING ENGINE" | tee -a $FLY
echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y 

%H:%M:%S" ) Cleaner script is running..." | tee -a $FLY;


# cleaner
busybox rm -f /data/anr/*.*
busybox rm -f 

/data/cache/*.*
busybox rm -f /data/log/*.*
busybox rm -f /data/local/tmp/*.*
busybox rm -f /data/mlog/*
busybox rm -f 

/data/tombstones/*
busybox rm -f /data/backup/pending/*
busybox rm -f /data/system/dropbox/*
busybox rm -rf 

/sdcard/LOST.DIR
busybox rm -f /cache/recovery/*
busybox rm -f /dev/log/main/*
chmod 700 /data/system/dropbox
busybox rm 

-f /data/system/usagestats/*
busybox chmod 700 /data/system/usagestats


echo "Cleaning done." | tee -a $FLY;

if [ -e 

/data/anr/*.* ]; then
  echo "-anr not cleaned" | tee -a $FLY; else
  echo "-anr cleaned" | tee -a $FLY
fi;
if [ -e 

/data/local/tmp/*.* ]; then
  echo "-local/tmp not cleaned" | tee -a $FLY; else
  echo "-local/tmp cleaned" | tee -a 

$FLY
fi;
if [ -e /data/cache/*.* ]; then
  echo "-cache not cleaned" | tee -a $FLY; else
  echo "-cache cleaned" | tee 

-a $FLY
fi;
if [ -e /data/last_log/*.* ]; then
  echo "-log not cleaned" | tee -a $FLY; else
  echo "-log cleaned" | tee 

-a $FLY
fi;
if [ -e /data/tombstones/*.* ]; then
  echo "-tombstones not cleaned" | tee -a $FLY; else
  echo "-

tombstones cleaned" | tee -a $FLY
fi;


echo "" | tee -a $FLY
echo "$( date +"%m-%d-%Y %H:%M:%S" ) All junk directories 

are now cleaned,Thanks to -CALIBAN666@XDA-!" | tee -a $FLY;
